### ISSUE TITLE
Issues with building the library

### ISSUE THREAD

**Issue by virto111** [golden-layout/golden-layout-ng-app#9] opened 2021-07-05 09:13 UTC
Hi Paul,
thank you for maintaining `Golden Layout` for Angular. It is amazing by your side and we appreciate it!

Just to mention that with the last several versions of the library we are not able to start the project.
There are errors during the build phase connected mainly with the types and with the provided number of arguments.

The first error is:

`Error: src/app/golden-layout-host.component.ts:4:3 - error TS2305: Module '"golden-layout"' has no exported member 'LogicalZIndex'.`

There are about 20 errors and if you need all the logs, just say and I will provide them.

I hope to give enough information. 

There are some issues with the versions I suppose and it is possible the issues we face to be only by our side,
but anyway, I decided to write it. 

Please let me know if you have any suspicions :-)

**Comment by pbklink** [comment] 2021-07-05 20:58
Hi Viktor,

The problem is at our end.

This repository has been updated to support the new [Virtual Components](https://github.com/golden-layout/golden-layout/issues/669) feature about to be released in Golden Layout. I have used this repository to test this feature.

The new Golden Layout readme for this feature can be viewed at [https://github.com/pbklink/golden-layout/tree/virtual-layout](https://github.com/pbklink/golden-layout/tree/virtual-layout) with the new component binding methods discussed [here](https://github.com/pbklink/golden-layout/tree/virtual-layout#binding-components)

The Golden Layout [Virtual Components Pull Request](https://github.com/golden-layout/golden-layout/pull/679) has been tested by myself and is waiting for @martin31821 to review and merge.

If you like, you can check out this Golden Layout PR in your development environment and recompile Golden Layout. This repository will then compile. Let me know if you come across any bugs or issues.

**Comment by virto111** [comment] 2021-07-06 07:16
Hi Paul,

Thank you for the immediate response.

That is fine for us since we might try it in couple of weeks and we currently are using a version from February.
Then we will try it again and let you know if something troubles us.

Thank you again.

**Comment by jeffreyschultz** [comment] 2021-07-07 03:33
Currently trying to learn the `Golden Layout` library and encountered this issue as well.

The library is very interesting, and I am hoping to be able to use it for our purpose.

Thank you!

**Comment by pbklink** [comment] 2021-07-19 19:29
Golden Layout 2.3.0 has now been published to NPM.  This includes the Virtual Components feature. I have updated this repository to use this release of Golden Layout and it now compiles again.

**Closed** 2021-12-20 19:59 UTC
